### ISSUE TITLE
Please make eidogo use query parameters instead of fragment identifiers to distinguish games.

### ISSUE THREAD

**Issue by jcdyer** [jkk/eidogo#5]
I would love to see eidogo use query parameters to identify games, like this:

```
http://eidogo.com/?game=abcdefg
```

instead of (or alternative to) the current implementation which uses fragment identifiers

```
http://eidogo.com/#abcdefg
```

This would solve a problem on reddit (which uses eidogo.com quite a bit), where reddit only allows a single story to link to a given page.  Fragments are intended to identify a location in a page, rather than a separate page, so reddit currently sees all fragments on the same base URL as the same page.  Using unique query strings would allow sites like reddit to distinguish between different games, and help users post review requests for their games.

**Comment by jkk** [comment]
Just moved Eidogo to a new server, and added a special redirect for uploaded SGFs. You can, for example, go here:

http://eidogo.com/tgntoZ6H

And it will redirect to the uploaded game at http://eidogo.com/#tgntoZ6H

(I literally just switched the DNS for eidogo.com, so if this doesn't work for you yet, it will once the DNS change propagates.)

**Comment by axd1967** [comment]
looks ike this is the last bit of activity on this project... pity. let's hope someone takes over...
